# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = ""
#  weight = 10

[[main]]
  name = "Home"
  url = "#"
  weight = 10

[[main]]
  name = "News"
  url = "#posts"
  weight = 50

[[main]]
  name = "Science"
  identifier = "science"
  url = "/science/"
  weight = 40

[[main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 30

  [[main]]
    name = "Company"
    parent = "about"
    url = "/about/"
    weight = 10
  [[main]]
    name = "People"
    parent = "about"
    url = "/about/#team"
    weight = 20
  [[main]]
    name = "FAQ"
    parent = "about"
    url = "/about/#faq"
    weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
